project:
  type: website

website:
  title: "semantic-segmentation"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  sidebar:
    style: "floating"
    search: true
    contents: auto


format:
  html:
    theme: cosmo
    css: styles.css

    



